# Generated by Django 5.0.6 on 2024-07-22 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='booklike',
            name='book',
        ),
        migrations.RemoveField(
            model_name='booklike',
            name='user',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookLike',
        ),
    ]
