# Generated by Django 5.0.6 on 2024-07-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_like_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
    ]
